project:
  group: slipper
  name: slipper

service:
  port: 8806
  context-path: /slipper

database:
  ip: localhost
  port: 3306
  name: slipper-base
  username: root
  password: root

druid:
  url-pattern: /druid/*
  username: admin
  password: admin

token:
  expire: 3600

redis:
  host: localhost
  port: 6379
  password:
